# Generated by Django 5.2.8 on 2025-11-29 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField()),
                ('actual_value', models.IntegerField()),
                ('plan_value', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('period', models.CharField(max_length=7)),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.plantype')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.specialization')),
            ],
            options={
                'unique_together': {('calculation_date', 'specialization', 'plan_type', 'period')},
            },
        ),
    ]
