# Generated by Django 5.2.8 on 2025-11-29 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_alter_visitaggregate_specialization'),
        ('kpi_calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiresult',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.misimportedspecialization'),
        ),
    ]
