# Generated by Django 5.2.8 on 2025-11-29 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_alter_visitaggregate_specialization'),
        ('kpi_calc', '0002_alter_kpiresult_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiresult',
            name='plan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.misimportedpurpose'),
        ),
    ]
