# Generated by Django 5.2.8 on 2025-11-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_alter_visitaggregate_specialization'),
        ('kpi_calc', '0003_alter_kpiresult_plan_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kpiresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kpiresult',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.misimporteddoctor'),
        ),
        migrations.AlterUniqueTogether(
            name='kpiresult',
            unique_together={('calculation_date', 'doctor', 'specialization', 'plan_type', 'period')},
        ),
    ]
