# Generated by Django 5.2.8 on 2025-11-28 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisImportedVisit',
            fields=[
                ('keyid', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyidmis', models.BigIntegerField(unique=True)),
                ('num', models.BigIntegerField()),
                ('casetypeid', models.IntegerField(blank=True, null=True)),
                ('dat', models.DateTimeField()),
                ('dat1', models.DateTimeField(blank=True, null=True)),
                ('vistype', models.IntegerField()),
                ('patientid', models.BigIntegerField(blank=True, null=True)),
                ('rootidmis', models.BigIntegerField(blank=True, null=True)),
                ('doctorid', models.BigIntegerField()),
                ('doctorname', models.CharField(max_length=255)),
                ('depid', models.BigIntegerField()),
                ('depname', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('diag_code', models.CharField(max_length=12)),
                ('diag_text', models.CharField(max_length=512)),
                ('manid', models.BigIntegerField()),
            ],
            options={
                'db_table': 'solution_med"."import_visit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.BigIntegerField()),
                ('doctor_name', models.CharField(max_length=255)),
                ('department_id', models.BigIntegerField()),
                ('department_name', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=7)),
                ('total_visits', models.IntegerField(default=0)),
                ('visits_by_purpose', models.JSONField(default=dict)),
                ('validated_docs_count', models.IntegerField(default=0)),
                ('total_docs_count', models.IntegerField(default=0)),
                ('visits_with_z_diagnosis', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.specialization')),
            ],
            options={
                'verbose_name': 'Агрегированные визиты',
                'verbose_name_plural': 'Агрегированные визиты',
                'unique_together': {('doctor_id', 'period')},
            },
        ),
    ]
