# Generated by Django 5.2.8 on 2025-11-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisImportedPurpose',
            fields=[
                ('keyid', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyidmis', models.BigIntegerField(unique=True)),
                ('tag', models.BigIntegerField()),
                ('code', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kpi"."purposes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MisImportedSpecialization',
            fields=[
                ('keyid', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyidmis', models.BigIntegerField(unique=True)),
                ('tag', models.BigIntegerField()),
                ('code', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kpi"."specialities',
                'managed': False,
            },
        ),
    ]
