# Generated by Django 5.2.8 on 2025-11-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_misimportedpurpose_misimportedspecialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisImportedDoctor',
            fields=[
                ('keyid', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyiddocdep', models.BigIntegerField(unique=True)),
                ('specidmis', models.BigIntegerField()),
                ('specnamemis', models.CharField(max_length=1000)),
                ('docnamemis', models.CharField(max_length=1000)),
                ('depidmis', models.BigIntegerField()),
                ('depnamemis', models.CharField(max_length=256)),
                ('manidmis', models.BigIntegerField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'solution_med"."import_doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MisImportedMan',
            fields=[
                ('keyid', models.BigAutoField(primary_key=True, serialize=False)),
                ('manidmis', models.BigIntegerField(unique=True)),
                ('text', models.CharField(max_length=256)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'solution_med"."import_man',
                'managed': False,
            },
        ),
    ]
