# Generated by Django 5.2.8 on 2025-11-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_misimporteddoctor_misimportedman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaggregate',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.misimportedspecialization'),
        ),
    ]
