# Generated by Django 5.2.8 on 2026-01-13 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('keyid', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=200, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('manid', models.IntegerField(blank=True, null=True, verbose_name='ID из МИС (man)')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'kpi"."users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('keyid', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100, unique=True, verbose_name='Название роли')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'kpi"."roles',
                'managed': False,
            },
        ),
    ]
