# Generated by Django 5.2.8 on 2025-11-28 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('plan_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.plantype')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.specialization')),
            ],
            options={
                'unique_together': {('year', 'specialization', 'plan_type')},
            },
        ),
    ]
