# Generated by Django 5.2.8 on 2025-11-28 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_misimporteddoctor_misimportedman'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiplan',
            name='plan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.misimportedpurpose'),
        ),
        migrations.AlterField(
            model_name='kpiplan',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.misimportedspecialization'),
        ),
    ]
