# Generated by Django 5.2.8 on 2025-11-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_kpiplan_plan_type_alter_kpiplan_specialization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpiplan',
            options={'managed': False},
        ),
    ]
