# Generated by Django 5.2.8 on 2025-11-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_kpiplan_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kpiplan',
            table='kpi"."plans',
        ),
    ]
